### ISSUE TITLE
TinyGPS unable to import into Arduino IDE

### ISSUE THREAD

**Issue by QuadRobo** [mikalhart/TinyGPS#2]
I have downloaded the version 13 of TinyGPS, TinyGPS-13. When I import into the Arduino IDE, it says that there shouldn't be a '-' in the file name, only numbers and letters are allowed. So I unzip and rename the folder within removing the '-' and rezip it under the name TinyGPS13. After importing, I typed #include <TinyGPS.h> into the IDE but it says that it doesn't exist. I am guessing that the renaming of the filename has affected it.

Is there a workaround?

**Comment by mikalhart** [comment]
Yes.  It's an unfortunate state of affairs that a Github release automatically adds a '-' to the folder name, which, as you observe, is not legal for Arduino.

The solution is fairly easy.  Unzip and install as before, but simply rename the directory (removing the -xxx from the end) before launching the Arduino IDE.  The folder should be in the "libraries" folder, like this:

![image](https://f.cloud.github.com/assets/504024/2091875/efa86148-8ea4-11e3-8b8d-10e78bf999b9.png)
