### ISSUE TITLE
request for clarification about some functions

### ISSUE THREAD

**Issue by varlux** [mikalhart/TinyGPS#8]
Hi everybody

first question: are latitudes and longitudes ALWAYS positive? Or.... are latitudes and longitudes always referred to Nord and East respectively?

(similar) second question: is altitude output always positive? Which is the output format for negative altitudes?

Thanks

**Comment by VK3TY** [comment]
__Numerically,_ _
- Latitudes are +ve above the equator, negative below.
- Longitudes are +ve East of of Greenwich (UK) and -ve West of Greenwich.

__Geographically,__
- Latitudes are expressed using absolute value suffixed with either
  "N" for North of the Equator or "S" if South of the Equator.
- Similarly with Longitude.  +ve are suffixed with an "E" or "W" if
  negative.

---

**Comment by varlux** [comment]
So....because the output of the library is suffix-less, it can be negative.....right?

**Comment by VK3TY** [comment]
If the output you are reading has no suffix, as much as I hate 
assumptions, you would have to assume that a negative value (for either 
a latitude or longitude) would suggest South or West respectively.

I hope that helps.
